youtube:
  api_key: bullshit-api-key
  channel_id: tczwag
  channel_list_parts:
    - id
    - test
  max_search_results: 20
  base_url: www.google.com

mongo:
  api_key: mongo-key
  host_address: www.mongo.com
  port: 8080
  username: pankaj-wimc
  password: SssWLVTnuAj65l3i
  database: wimc
  collection_prefix: search_results